config/routes.rb
Rails.application.routes.draw do
  

  get 'home/index'

  get 'user_sessions/create'
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout

  resources :users
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end

  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title>Krow </title>
<link href="https://fonts.googleapis.com/css?family=Oswald|Pacifico" rel="stylesheet">
  <%= stylesheet_link_tag    "application" %>
  
  <%= javascript_include_tag "vendor/modernizr" %>
  
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
 
  <%= csrf_meta_tags %>
</head>

<body>
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><% if logged_in? %>
          <%= link_to "Krow", todo_lists_path%>
          <% else %>
          <%= link_to "Krow", root_path%>

          <% end%>
        </h1>
      </li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <% if logged_in? %>
        <li class="active"><%= link_to "Todo Lists", todo_lists_path%></li>
        <li><%= link_to "Sign Out", logout_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign Up", new_user_path%></li>
        <li><%= link_to "Sign In", new_user_session_path%></li>
        <% end %>
        <li class="has-dropdown">

        </li>
      </ul>

      <!-- Left Nav Section -->
      <ul class="left">

      </ul>
    </section>
  </nav>
  <div id="grad">
    <div class="row">
      <div class=" large-8 columns"> 
        <% flash.each do |type, message| %>
        <div class ="alert flash <%= type %>" id="flash">
          <%= message %>
        </div>
        <% end %>

        <%= yield %>
      </div>
      <div class="large-4 columns" >
        <div class="column">
          <h1>About us</h1>
          <div id="about-us">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          </div>
          
            <h1>Advertisements</h1>
            <div id="advert">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          </div>
        </div>
      </div>
    </div>
<footer>

</footer>
  </div>

  <script type="text/javascript">
  $('#flash').fadeOut(4000);
 $(".top-bar").fadeIn()
.css({top:-1000,position:'relative'})
.animate({top:0}, 1500, function() {
    //callback
});

$("#grad").fadeIn()
.css({top:1000,position:'relative'})
.animate({top:0}, 800, function() {
    //callback
});
 // $("#grad h1").fadeIn()
//.css({top:1000,position:'relative'})
//.animate({top:0}, 1500, function() {
    //callback
//});
 $("#grad h1").animate({ opacity: 0.9
    // Animation complete.
  });

 
  </script>
</body>
</html>

app/views/layouts/home_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Krow</title>
	 <link href="https://fonts.googleapis.com/css?family=Oswald|Pacifico" rel="stylesheet">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	<%= csrf_meta_tags %>
</head>
<body>

	


	<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Krow", root_path%></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <% if logged_in? %>
			<li><%= link_to "Todo Lists", todo_lists_path%></li>
			<li><%= link_to "Sign Out", logout_path, method: :delete %></li>
			<% else %>
			<li><%= link_to "Sign Up", new_user_path%></li>
			<li><%= link_to "Sign In", new_user_session_path%></li>
			<% end %>
      <li class="has-dropdown">
        
      </li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      
    </ul>
  </section>
</nav>

	
<div id="grad-home">
	<%= yield %>
</div>
<footer>
&copy; TekSavant 2016
</footer>

	 <script type="text/javascript">
  
  
  $(".top-bar").fadeIn()
.css({top:-1000,position:'relative'})
.animate({top:0}, 1500, function() {
    //callback
});
$("#grad-home").fadeIn()
.css({top:1000,position:'relative'})
.animate({top:0}, 800, function() {
    //callback
});
  $("#grad-home h1").fadeIn()
.css({top:1000,position:'relative'})
.animate({top:0}, 1500, function() {
    //callback
});
  $("#grad-home h4").fadeIn()
.css({top:1000,position:'relative'})
.animate({top:0}, 1300, function() {
    //callback
});
$("#grad-home a").fadeIn()
.css({top:1000,position:'relative'})
.animate({top:260}, 1300, function() {
    //callback
});

 
  </script>
	


</body>
</html>